[package]
name = "palomadex"
version = "0.1.0"
authors = ["Volume Finance"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-schema.workspace = true
cosmwasm-std = { workspace = true, features = ["cosmwasm_1_1"] }
cw-storage-plus.workspace = true
cw2.workspace = true
cw20.workspace = true
cw-utils.workspace = true
itertools.workspace = true
schemars.workspace = true
serde.workspace = true
thiserror.workspace = true
cw-asset = "4.0.0"
uint = "0.10.0"

[dev-dependencies]
cw-multi-test = "2.0.0"
test-case = "3.1.0"
