[package]
name = "palomadex-mocks"
version = "0.2.0"
authors = ["Volume Finance"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(tarpaulin_include)"] }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
palomadex = { path = "../palomadex" }
palomadex-factory = { path = "../../contracts/factory" }
palomadex-native-coin-registry = { path = "../native_coin_registry" }
palomadex-pair = { path = "../../contracts/pair" }
palomadex-pair-stable = { path = "../../contracts/pair_stable" }
cw20-base = "1"
cosmwasm-schema = "1.2.5"
cosmwasm-std = "1.2.5"
cw-multi-test = "1.2.0"
injective-cosmwasm = "0.2"
schemars = "0.8.1"
serde = "1.0"
cw-utils = "1.0"
cw20 = "0.15"
anyhow = "1.0"
cw3 = "1.0"
cw1-whitelist = { version = "1.1.2", features = ["library"] }
